import { Dimensions, StyleSheet } from 'react-native';

const { height: SCREEN_H } = Dimensions.get('window');

/** @deprecated Use flex hero (AlbumPhotosHeroCarousel) — kept for previews only */
export const ALBUM_HERO_H = Math.round(SCREEN_H * 0.46);

export const ALBUM_THUMB_W = 52;
export const ALBUM_THUMB_H = 42;

export const albumChromeStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f8fafc' },
  header: {
    backgroundColor: '#fff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e2e8f0',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBack: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBackGallery: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroOverlayBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(15,23,42,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  heroOverlayBtnLight: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.88)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15,23,42,0.08)',
  },
  headerCenter: { flex: 1, alignItems: 'center', paddingHorizontal: 8 },
  headerTitle: { fontSize: 15, fontWeight: '600', color: '#0f172a' },
  headerSub: { fontSize: 11, color: '#94a3b8', marginTop: 1 },
  footer: {
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e2e8f0',
    paddingHorizontal: 14,
    paddingTop: 8,
    gap: 6,
    flexShrink: 0,
  },
  footerGallery: {
    backgroundColor: 'transparent',
    borderTopWidth: 0,
    paddingHorizontal: 14,
    paddingTop: 8,
    gap: 6,
    flexShrink: 0,
  },
  metaCard: {
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#f1f5f9',
    flexShrink: 0,
  },
  metaCardTransparent: {
    backgroundColor: 'transparent',
    borderTopWidth: 0,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
    flexShrink: 0,
  },
  metaTitle: { fontSize: 15, fontWeight: '600', color: '#0f172a', letterSpacing: -0.2, marginBottom: 4 },
  metaTitleLight: { fontSize: 15, fontWeight: '600', color: '#f8fafc', letterSpacing: -0.2, marginBottom: 4 },
  metaRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginBottom: 2 },
  metaText: { fontSize: 12, color: '#64748b', fontWeight: '500' },
  metaTextAccent: { fontSize: 12, color: '#0d9488', fontWeight: '500' },
  metaMembers: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  metaAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#fff',
    backgroundColor: '#e2e8f0',
  },
  metaCount: { fontSize: 11, color: '#0d9488', fontWeight: '600' },
  metaCountLight: { fontSize: 11, color: '#5eead4', fontWeight: '600' },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f0fdfa',
    borderWidth: 1.5,
    borderColor: '#99f6e4',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionBtnOutline: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#0d9488',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionBtnFull: {
    flexDirection: 'row',
    backgroundColor: '#f0fdfa',
    borderWidth: 1.5,
    borderColor: '#99f6e4',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionBtnText: { fontSize: 12, fontWeight: '600', color: '#0d9488' },
  thumbDeleteBtn: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(220,38,38,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnGallery: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderWidth: 1.5,
    borderColor: 'rgba(13,148,136,0.35)',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionBtnOutlineGallery: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderWidth: 1.5,
    borderColor: 'rgba(13,148,136,0.45)',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionBtnFullGallery: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderWidth: 1.5,
    borderColor: 'rgba(13,148,136,0.35)',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  thumbStrip: {
    backgroundColor: '#fff',
    paddingVertical: 5,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#f1f5f9',
    flexShrink: 0,
  },
  thumbStripTransparent: {
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
    paddingVertical: 5,
    flexShrink: 0,
  },
  albumSubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 5,
    backgroundColor: '#fff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e2e8f0',
    flexShrink: 0,
  },
  albumSubHeaderGallery: {
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
  },
  albumSubHeaderSide: { width: 88, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 6 },
});
